server:
  # https 加密端口号 8080
  port: 443
  ssl:
    # SSL 证书路径，classpath 必不可少
    key-store: classpath:6759745_zhouyunji.top.pfx
    # SSL 证书密码
    key-store-password: QA8WNSB9
    # 证书类型
    key-store-type: PKCS12
    servlet:
      context-path: /recycle
spring:
#  静态资源访问路径配置
  resources:
    static-locations: classpath:templates/,classpath:static/
  mvc:
    static-path-pattern: /static/**

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.96.0.106:3306/recycle
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
mybatis:
  mapper-locations: classpath:mapper/*.xml


#  config-location: classpath:mybatis/mybatis-config.xml


