server:
  port: 8088
  servlet:
    context-path: /QR
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://182.92.211.22:3306/mydatabase
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml


